//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAPI.TestApiEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tokenmanagment
    {
        public int id_token { get; set; }
        public string access_token { get; set; }
        public int expire_token { get; set; }
        public string refresh_token { get; set; }
        public string status_token { get; set; }
    }
}
